### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by torstenberg** [apnadkarni/ruff#44]
What a nice package! I need it in German, so I added localization to the package. I added a `-locale` option to the ::ruff::document command and added a minimal set of German localizations (for procedures only). I have put the translated strings into ruff.tcl, you may want to have them in a separate file for convenience.

Would be nice to have such thing included into the next official release.

[ruff-localization.zip](https://github.com/apnadkarni/ruff/files/6021708/ruff-localization.zip)

**Comment by apnadkarni** [comment]
Thanks for the patch. Will take a look at it for the next release.

**Comment by apnadkarni** [comment]
Added -locale support with couple of changes:

- messages are in separate directory as suggested.
- The **Returns** keyword handling. If followed by a colon, only the succeeding text is included in the paragraph, not the Returns word itself. For example

```
Returns 1 if the value is positive and 0 otherwise.
```

Will result in 

**Return value**

Returns 1 if the value is positive and 0 otherwise.

While (notice the colon)

```
Returns: If the value is positive, returns 1, else 0.
```

results in

**Return value**

If the value is positive, returns 1, else 0.

Thus for localization you probably want to use the latter form. Note the check does not make use of the locale setting as "en" as in the patch.

**Comment by apnadkarni** [comment]
Torsten, I added a couple of translations to the de.msg file. Please check for correctness.

**Comment by torstenberg** [comment]
This is great, thanks! I have checked the translations and they are all correct.
